name: built_reducer
description: Generates actions and a reducer from a set of pure functions.
version: 0.5.1
homepage: https://github.com/aloisdeniel/reducer

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  recase: ^3.0.0
  meta: ^1.1.8
  analyzer: ^0.39.0
  build: '>=0.12.6 <2.0.0'
  build_config: '>=0.2.6 <0.5.0'
  source_gen: ^0.9.0
  reducer: ^0.5.1
  code_builder: ^3.3.0
  dart_style: ^1.3.6

dev_dependencies:
  build_runner: ^1.0.0
  pedantic: ^1.8.0
  test: ^1.6.0
