name: reducer
description: Generates actions and a reducer from a set of pure functions.
version: 0.5.1
homepage: https://github.com/aloisdeniel/reducer

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
